sensors:
  - sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater
    point_cloud_topic: /realsense/depth/points
    max_range: 1.0
    point_subsample: 1
    padding_offset: 0.08
    padding_scale: 1.08
    max_update_rate: 50.0
    filtered_cloud_topic: filtered_cloud
    ns: realsense
