sensors:
  - sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater
    point_cloud_topic: /realsense/depth/points
    max_range: 10.0
    point_subsample: 10
    padding_offset: 0.1
    padding_scale: 1.0
    max_update_rate: 50.0  
    filtered_cloud_topic: filtered_cloud
    ns: realsense
